# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='open_date',
        ),
        migrations.AddField(
            model_name='house',
            name='opened_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='opened date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('close', 'close'), ('Ready', 'ready')], default='ready', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='house',
            name='accessibility',
            field=models.TextField(blank=True, null=True, verbose_name='accessibility'),
        ),
        migrations.AlterField(
            model_name='house',
            name='amenity',
            field=models.TextField(blank=True, null=True, verbose_name='amenity'),
        ),
        migrations.AlterField(
            model_name='house',
            name='common_service',
            field=models.TextField(blank=True, null=True, verbose_name='common service'),
        ),
        migrations.AlterField(
            model_name='house',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='house',
            name='private_service',
            field=models.TextField(blank=True, null=True, verbose_name='private service'),
        ),
        migrations.AlterField(
            model_name='house',
            name='sort_score',
            field=models.IntegerField(default=0, verbose_name='sort score'),
        ),
        migrations.AlterField(
            model_name='house',
            name='transportation',
            field=models.TextField(blank=True, null=True, verbose_name='transportation'),
        ),
    ]
