# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20170730_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='search_tag',
            field=models.ManyToManyField(blank=True, to='house.SearchTag', verbose_name='tag'),
        ),
    ]
