# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20170730_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='position',
        ),
    ]
