# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_remove_house_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='position',
            field=geoposition.fields.GeopositionField(default=1.0, max_length=42, verbose_name='position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='address'),
        ),
    ]
