# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20170730_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='HousePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='house_photo', verbose_name='photo')),
                ('sort_score', models.IntegerField(default=0, verbose_name='sort score')),
            ],
            options={
                'verbose_name_plural': 'House photos',
                'verbose_name': 'House photo',
                'ordering': ('sort_score',),
            },
        ),
        migrations.CreateModel(
            name='PhotoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('sort_score', models.IntegerField(default=0, verbose_name='sort score')),
            ],
            options={
                'verbose_name_plural': 'Photo groups',
                'verbose_name': 'Photo group',
                'ordering': ('sort_score',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('sex', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=20, verbose_name='sex')),
                ('capacity', models.IntegerField(default=0, verbose_name='capacity')),
                ('area', models.FloatField(default=0.0, verbose_name='area')),
                ('month_rent', models.IntegerField(verbose_name='monthly rent')),
                ('month_manage_fee', models.IntegerField(verbose_name='monthly management fee')),
                ('pre_util_charge', models.IntegerField(verbose_name='prepayment utility charge')),
                ('deposit', models.IntegerField(verbose_name='deposit')),
                ('moving_month', models.IntegerField(verbose_name='moving month')),
                ('availability', models.BooleanField(default=True, verbose_name='availability')),
                ('sort_score', models.IntegerField(default=0, verbose_name='sort score')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'verbose_name': 'Room',
                'ordering': ('sort_score',),
            },
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ('sort_score',), 'verbose_name': 'House', 'verbose_name_plural': 'Houses'},
        ),
        migrations.RemoveField(
            model_name='house',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='house',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='house',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='room',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House', verbose_name='house'),
        ),
        migrations.AddField(
            model_name='photogroup',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House', verbose_name='house'),
        ),
        migrations.AddField(
            model_name='housephoto',
            name='photo_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.PhotoGroup', verbose_name='photo_group'),
        ),
    ]
