# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20170730_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housephoto',
            options={'verbose_name': 'House photo', 'verbose_name_plural': 'House photos'},
        ),
        migrations.AlterModelOptions(
            name='photogroup',
            options={'verbose_name': 'Photo group', 'verbose_name_plural': 'Photo groups'},
        ),
        migrations.RemoveField(
            model_name='housephoto',
            name='sort_score',
        ),
        migrations.RemoveField(
            model_name='photogroup',
            name='sort_score',
        ),
        migrations.AddField(
            model_name='housephoto',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='photogroup',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
