# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20170730_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housephoto',
            options={'ordering': ['position'], 'verbose_name': 'House photo', 'verbose_name_plural': 'House photos'},
        ),
        migrations.AlterModelOptions(
            name='photogroup',
            options={'ordering': ['position'], 'verbose_name': 'Photo group', 'verbose_name_plural': 'Photo groups'},
        ),
    ]
