# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_auto_20170730_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='trading_area',
            new_name='main_title',
        ),
        migrations.RemoveField(
            model_name='house',
            name='name',
        ),
        migrations.RemoveField(
            model_name='house',
            name='opened_date',
        ),
        migrations.AddField(
            model_name='house',
            name='house_name',
            field=models.CharField(default='준비중', max_length=30, verbose_name='house name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='opened_date_char',
            field=models.CharField(default='준비중', max_length=50, verbose_name='opened date char'),
            preserve_default=False,
        ),
    ]
