# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_auto_20170803_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['my_order'], 'verbose_name': 'House', 'verbose_name_plural': 'Houses'},
        ),
        migrations.RemoveField(
            model_name='house',
            name='sort_score',
        ),
        migrations.AddField(
            model_name='house',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='my_order'),
        ),
        migrations.AlterField(
            model_name='house',
            name='main_title',
            field=models.CharField(max_length=50, verbose_name='main title'),
        ),
    ]
