# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_auto_20170805_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='is main'),
        ),
    ]
