# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_house_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='availability',
        ),
        migrations.AddField(
            model_name='room',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='is open'),
        ),
    ]
