# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_auto_20170805_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_immediately',
            field=models.BooleanField(default=False, verbose_name='is immediately'),
        ),
        migrations.AlterField(
            model_name='room',
            name='moving_month',
            field=models.CharField(max_length=50, verbose_name='moving month'),
        ),
    ]
