# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number1')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='memo')),
                ('status', models.CharField(choices=[('progress', 'progress'), ('complete', 'complete'), ('cancel', 'cancel')], max_length=20, verbose_name='status')),
                ('inquiry_route', models.CharField(blank=True, max_length=30, null=True, verbose_name='inquiry route')),
            ],
            options={
                'verbose_name': 'Partner inquiry',
                'verbose_name_plural': 'Partner inquiries',
            },
        ),
    ]
