# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_tenantinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerinquiry',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='tenantinquiry',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='phone number'),
        ),
    ]
