# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_auto_20170801_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinquiry',
            name='is_waiting',
            field=models.BooleanField(default=False, verbose_name='is waiting'),
        ),
        migrations.AlterField(
            model_name='tenantinquiry',
            name='house',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='house.House', verbose_name='house'),
        ),
    ]
