# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_auto_20170805_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerinquiry',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('progress', 'progress'), ('complete', 'complete'), ('cancel', 'cancel')], max_length=20, verbose_name='status'),
        ),
    ]
