# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('context', models.TextField(verbose_name='context')),
                ('photo', models.ImageField(upload_to='news_photo', verbose_name='photo')),
                ('link_url', models.URLField(verbose_name='link url')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'MainNews',
                'verbose_name_plural': 'MainNewses',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'TopBanner',
                'verbose_name_plural': 'TopBanners',
            },
        ),
    ]
