# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['my_order'], 'verbose_name': 'MainNews', 'verbose_name_plural': 'MainNewses'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='position',
        ),
        migrations.AddField(
            model_name='news',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
