# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '상권', 'verbose_name_plural': '상권(들)'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': '도시', 'verbose_name_plural': '도시(들)'},
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, verbose_name='상권명'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Province', verbose_name='도시'),
        ),
        migrations.AlterField(
            model_name='province',
            name='latitude',
            field=models.FloatField(verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='province',
            name='longitude',
            field=models.FloatField(verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=50, verbose_name='도시명'),
        ),
    ]
